### ISSUE TITLE
test render on netlify keeps on erroring after move to d4dm organisation

### ISSUE THREAD

**Issue by ernestguevarra** [data4decisionmakers/data-concepts-applications#24]
add this to `test-render.yml`:

```
permissions:
  contents: write
  deployments: write
  pull-requests: write
```
